services:
  db:
    image: postgres:17
    container_name: test_pgdb
    ports:
     - "5433:5432"
    environment:
      POSTGRES_DB: psz
      POSTGRES_USER: uros
      POSTGRES_PASSWORD: n21wVyLRCCckFotr
    
    volumes:
      - test-pgdb-data:/var/lib/postgresql/data
      - ./baza:/docker-entrypoint-initdb.d:ro

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin4_test_container
    ports:
      - "8889:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: uros@domain-name.com
      PGADMIN_DEFAULT_PASSWORD: n21wVyLRCCckFotr
    volumes:
      - pgadmin-test-data:/var/lib/pgadmin

volumes:
  test-pgdb-data:
  pgadmin-test-data:
